### ISSUE TITLE
Integrate documentation with ui-screen-shooter

### ISSUE THREAD

**Issue by fulldecent** [rhaining/itc-localized-screenshot-uploader#5]
See https://github.com/fulldecent/ui-screen-shooter

The filename output there should match the input here (see #4). And this should be seamless from:
- Update app
- Make screenshots (ui-screen-shooter)
- Prepare upload (itc-localized-screenshot-uploader)
- Do upload (iTunes transporter)
- Mother fucking drinking time

**Comment by rhaining** [comment]
huzzah! sorry bout the delay :)

**Comment by fulldecent** [comment]
FYI, our merge request https://github.com/rhaining/itc-localized-screenshot-uploader/issues/5 was accepted and now the two projects work great together.
